// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNHBgwXDvt28zryF4SnwxOv9i0wnad-zU',
    appId: '1:557308803278:web:597b81901347bf9ab1789f',
    messagingSenderId: '557308803278',
    projectId: 'finance-5d1fa',
    authDomain: 'finance-5d1fa.firebaseapp.com',
    storageBucket: 'finance-5d1fa.firebasestorage.app',
    measurementId: 'G-YTRG0N5ZQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHH9xS7bcNWa1iiPIGxGcnZiffiM_6Sqg',
    appId: '1:557308803278:android:42e52e23e9ddda70b1789f',
    messagingSenderId: '557308803278',
    projectId: 'finance-5d1fa',
    storageBucket: 'finance-5d1fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArz3enu8_3XlouHOWnG6lePLGc6j4Pyg0',
    appId: '1:557308803278:ios:0059db974ab55cdeb1789f',
    messagingSenderId: '557308803278',
    projectId: 'finance-5d1fa',
    storageBucket: 'finance-5d1fa.firebasestorage.app',
    iosBundleId: 'com.example.revesion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArz3enu8_3XlouHOWnG6lePLGc6j4Pyg0',
    appId: '1:557308803278:ios:0059db974ab55cdeb1789f',
    messagingSenderId: '557308803278',
    projectId: 'finance-5d1fa',
    storageBucket: 'finance-5d1fa.firebasestorage.app',
    iosBundleId: 'com.example.revesion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNHBgwXDvt28zryF4SnwxOv9i0wnad-zU',
    appId: '1:557308803278:web:0db93e0fe93a243fb1789f',
    messagingSenderId: '557308803278',
    projectId: 'finance-5d1fa',
    authDomain: 'finance-5d1fa.firebaseapp.com',
    storageBucket: 'finance-5d1fa.firebasestorage.app',
    measurementId: 'G-FNWR50BEE4',
  );
}
